#!/usr/bin/env bash

# create new multipass instance
#
#	sd mp new


set -euo pipefail

NAME=$(gum input --placeholder "instance name")

echo "Number of Cores:"
CPU=$(gum choose --item.foreground 250 "1" "2" "4" "8")
echo "Memory:"
MEM=$(gum choose --item.foreground 250 "2G" "4G" "8G" "16G")

echo "Disk:"
DISK=$(gum choose --item.foreground 250 "10G" "20G" "50G" "100G")

echo "Use Bridged Network?"

YES="Yes"
NO="No"

CHOICE=$(gum choose "$YES" "$NO")

if [ "$CHOICE" != "$NO" ]; then
    BRIDGED="--bridged"
fi

echo "Choose cloud-init:"
CLOUDINIT=$(ls ~/virtualization/cloud/*.yaml | gum choose)

echo "Instance: $NAME"
echo "    Disk: $DISK"
echo "     Mem: $MEM"
echo "     CPU: $CPU"
echo " Bridged: $BRIDGED"
echo "    Init: $CLOUDINIT"

multipass launch "$BRIDGED" --name "$NAME" --cpus "$CPU" --disk "$DISK" --mem "$MEM" --cloud-init "$CLOUDINIT" 22.04
